'use client';
import { Title, Text, Anchor, Button } from '@mantine/core';
import classes from './Welcome.module.css';
import Image from 'next/image';
import { IconArrowRight } from '@tabler/icons-react';

export function Welcome() {
  return (
    <>
      <Text c="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="lg">
        🥇 Winner of the Base{' '}
        <a
          target="_blank"
          href="https://base.mirror.xyz/p_A3ZxaBUEcpWwTf9_Yg-jnlOro8m8Ypc8LEDnA_ZRk"
        >
          Onchain Summer Buildathon
        </a>
        ! 🥇
      </Text>

      <Title className={classes.title} ta="center" mt="lg" mb="lg">
        {/* This is{' '} */}
        {/* <Text inherit variant="gradient" component="span" gradient={{ from: 'blue', to: 'orange' }}>
          anglez.xyz
        </Text> */}
        <Image src="/anglez-logo-treatment-2.png" alt="anglez text" width={353} height={205} />
      </Title>
      <center>
        <Image src="/anglez-animated-1.gif" alt="anglez animation" width={300} height={300} />
        <Text c="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="lg">
          Abstract, generative NFT art that is fully on-chain and 100% generated by Solidity code.
          Created by{' '}
          <a target="_blank" href="https://www.x.com/volstrate">
            volstrate
          </a>
          , customised by you!
          <br></br>
        </Text>

        <Text c="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="lg">
          Only 512 anglez can ever be minted.
        </Text>

        <Button mt="lg" component="a" href="/create" rightSection={<IconArrowRight size={14} />}>
          Get started creating anglez!
        </Button>
      </center>
    </>
  );
}
